### ISSUE TITLE
Why the use of curl.exe?

### ISSUE THREAD

**Issue by csears** [vmkdaily/vFlux-Stats-Kit#1]
Nice work on the project. I love the idea of getting vCenter metrics into Influx.

Looking at the PS code, I was curious why you chose to shell out to curl.exe instead of using built-in options like Invoke-RestMethod, Invoke-WebRequest, or System.Net.WebClient.

Thanks!

**Comment by vmkdaily** [comment]
Thanks so much for the feedback!

I initially planned to use Invoke-WebRequest or similar, but the only examples I could find (i.e. http://wahlnetwork.com/2015/04/29/building-a-dashboard-with-grafana-influxdb-and-powercli/) were based on InfluxDB v0.8 Line Protocol.  Since JSON writes are deprecated with InfluxDB ~v0.9 and later, I then found this 'working' approach from D'Haese Willem / Matt Hodge (using curl.exe).

Not to mention, their quoting and escaping is wonderful.  After surviving years of torture making plink work in Powershell, I really appreciated and respected the fact that someone already did that for me.

I should revisit those cmdlets you mentioned (even though they are intimidating) and perhaps even Telegraph (from InfluxData), which it looks like Matt is using now.

**Comment by steverweber** [comment]
https://github.com/uwaterloo-s8weber/influxdb-metrics-vmware
here is a solution that uses invoke-WebRequest.

**Comment by vmkdaily** [comment]
Thanks @steverweber!  Very cool!
