### ISSUE TITLE
Vmware ststs issue

### ISSUE THREAD

**Issue by ghost** [vmkdaily/vFlux-Stats-Kit#5]
Hi

installed everything as shown on the document and the scripts all worked fine...but could not find any data on the database. could you please help

**Comment by vmkdaily** [comment]
Apologies for the delay!  Did you get up and running?  My guess is you need to manually select the desired InfluxDB database in Grafana.  I removed the example dashboard (json) since that may have been confusing.  You need to create your own.   Let me know if I can help.  Also check out this user contributed blog post on usage https://www.jorgedelacruz.es/2017/06/12/en-busca-del-dashboard-perfecto-influxdb-telegraf-y-grafana-parte-vii-monitorizar-vsphere/

**Comment by vmkdaily** [comment]
Just checking in to see if you have tried again lately.

The latest REST scripts have comments that are more accurate in the preferences section. Due to copy paste of the comments, I previously had something like:

> To follow my examples, set to 'compute' here

That comment was on both the iops and compute script.  If you followed it literally, that could be one reason it did not work before.

Either way, please ensure you have created both of the required databases (one for iops and one for compute).  You can add as many as you would like to get more granular. Names are not important, but all must be accounted for in your preferences section at the top of the scripts.

**Comment by vmkdaily** [comment]
Closing this old issue due to inactivity.
